server:
  port: 8000
  servlet:
    context-path: /plat-peer2peer
spring:
  application:
    name: plat-peer2peer
  data:
    mongodb:
      uri: mongodb://msgplatform:msg123456@172.27.255.33:27020/patral
#      uri: mongodb://msgplatform:msg123456@172.29.12.78:27017/patral

  redis:
#    host: 172.29.12.79
    host: 172.27.255.35
    #    host: 127.0.0.1
    port: 6379
    password: cmdb123.
    database: 15
    timeout: 30000
    jedis:
      pool:
        # 连接池中的最大空闲连接
        max-idle: 100
        # 连接池中的最小空闲连接
        min-idle: 10
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8

com:
  alipay:
    sofa:
      rpc:
        bolt-port: 12200
        rest-port: 12100
        rest-context-path: /peer2peer

logging:
  path: ./logs/m-p2p-log/sofa
  config: classpath:log4j2.xml
#自定义变量
self:
  url:
    im: http://172.27.255.92/post_im_message
#    im: http://172.29.12.100/post_im_message


