apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
  app: plat-peer2peer-release
  name: plat-peer2peer-release
  namespace: extdev
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  template:
    metadata:
      labels:
        app: plat-peer2peer-release
    spec:

      containers :
        - name: plat-peer2peer-release
          image: reg.yondervision.com.cn:8081/rdgrp/plat-peer2peer-release:$BUILD_NUMBER
          command: ["java", "-jar",
                    "-server",
                    "-XX:+UseConcMarkSweepGC",
                    "-XX:+UseParNewGC",
                    "-XX:+DisableExplicitGC",
                    "-XX:CMSInitiatingOccupancyFraction=68",
                    "-verbose:gc",
                    "-XX:+PrintGCDetails",
                    "-XX:+PrintGCDateStamps",
                    "-XX:+HeapDumpOnOutOfMemoryError",
                    "-XX:HeapDumpPath=/var/k8s/logs/plat-peer2peer-release",
                    "-XX:ErrorFile=/var/k8s/logs/plat-peer2peer-release/err_pid%p.log",
                    '-Xmx8192m',
                    '-Xms1024m',
                    "-Xss512k",
                    "-XX:PermSize=256m",
                    "-XX:MaxPermSize=512m",
                    "-Djava.awt.headless=true",
                    "-DLog4jLogEventFactory=com.wish.plat.sofatracer.log4j2.CommonMsgEventFactory",
                    "/var/k8s/plat-peer2peer-service.jar"]
          lifecycle:
            preStop:
              exec:
                command: ["sleep", "15"]
          env:
            - name: JAVA_OPTS
              value: -server  -Xms1024m -Xmx8192m -Djava.awt.headless=true -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/data/plat-datadriven/log/plat-peer2peer_oom.hprof -DLog4jLogEventFactory=com.wish.plat.sofatracer.log4j2.CommonMsgEventFactory
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /plat-peer2peer/actuator/readiness
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 60  #容器启动后第一次执行探测是需要等待多少秒。
            periodSeconds: 5          #执行探测的频率。默认是10秒，最小1秒。
            timeoutSeconds: 1         #探测超时时间。默认1秒，最小1秒。
            failureThreshold: 5       #探测成功后，最少连续探测失败多少次才被认定为失败。默认是3。最小值是1。\
          livenessProbe:      #livenessProbe是K8S认为该pod是存活的，不存在则需要kill掉，然后再新启动一个，以达到RS指定的个数。
            httpGet:
              path: /plat-peer2peer/actuator/readiness
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          resources:
            requests:
              memory: 1288Mi
              cpu: 0.1
            limits:
#              memory: 8192Mi
              memory: 2500Mi
              cpu: 2
          volumeMounts:
            - name: plat-data
              mountPath: /data/
            - name: tmp-volume
              mountPath: /tmp/
            - name: log-volume  #日志目录映射配置
              mountPath: /var/k8s/logs

      volumes:
        - name: plat-data
          emptyDir: {}
        #          persistentVolumeClaim:
        #            claimName: plat-data-claim
        - name: tmp-volume
          emptyDir: {}
        - name: log-volume
          hostPath:
            path: /data/logs/

      imagePullSecrets:
        - name: regextuser01

      nodeSelector:
        points: "extnode"


---
apiVersion: v1
kind: Service
metadata:
  name: plat-peer2peer-release
  namespace: extdev
spec:
  type: NodePort
  ports:
    - name: plat-peer2peer-rest
      port: 12100
      targetPort: 12100
    - name: plat-peer2peer-bolt
      port: 12200
      targetPort: 12200
    - name: plat-peer2peer-http
#      port: 31081
      port: 8000
      targetPort: 8000
#      nodePort: 31081

  selector:
    app: plat-peer2peer-release
  sessionAffinity: ClientIP
